### ISSUE TITLE
Dumping object issue

### ISSUE THREAD

**Issue by Moon4u** [take-cheeze/mruby-marshal#11]
So, I have the following code:

```
class B
  def initialize
    @a = 3
  end
end
a = B.new
Marshal.dump(a)
f = Marshal.load(a)
```

This hits assert(false) in the symbol function after the load function

mruby bytes

```
> Marshal.dump(B.new).bytes
 => [4, 8, 111, 58, 6, 66, 59, 0, 0]
```

ruby bytes

```
> Marshal.dump(B.new).bytes.to_a
=> [4, 8, 111, 58, 6, 66, 6, 58, 7, 64, 97, 105, 8]
```

I'm currently trying to figure out why this happens, but the Marshal module is new for me. Any help is welcome.

**Comment by take-cheeze** [comment]
Sorry. This seems to caused by bad implementation.
Will fix soon.

BTW `bytes` isn't required since string printing of ruby is useful in marshal format checking.
