### ISSUE TITLE
Error when built

### ISSUE THREAD

**Issue by torsakch** [take-cheeze/mruby-marshal#16]
I got the error when I build it with android toolchain.

`mrbgems/mruby-marshal/src/marshal.cpp:10:10: fatal error: 'cassert' file not found
#include <cassert>
         ^
1 error generated.`

Can you recommend the way to solve the error? Thank you.

**Comment by take-cheeze** [comment]
@torsakch 
Somehow C++ standard headers isn't in your C++ flags (`cassert` is nearly just `assert.h`).
And I've never tried this mrbgem in android.

**Comment by take-cheeze** [comment]
@torsakch Any updates to this?
Maybe you are using C compiler to compile C++ code.

**Comment by take-cheeze** [comment]
No response so closing.
