### ISSUE TITLE
Marshaling of Structures

### ISSUE THREAD

**Issue by catsidhe** [take-cheeze/mruby-marshal#8]
Given `MyStruct = Struct.new(:field)`:
- `Marshal.dump(MyStruct.new)` crashes mruby;
- `Marshal.dump(MyStruct.new([0.0, 0.0]))` in ruby, try loading in mruby: `Invalid link ID: 2 (table size: 2) (ArgumentError)`

**Comment by take-cheeze** [comment]
Currently `Struct` support is under construction (as I remember).
Has little relation to `is_struct` function which was fixed recently.
